<div>
    {% if not is_index %}
        <div style="text-align:center;color: #ccc;font-size:14px;margin-top: 2em">
          <p style="overflow: hidden; width: 100%; white-space: nowrap; margin: 0;">------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
          <div>本文结束 <i class="fa fa-paw"></i> 感谢您的阅读</div>
          <p style="overflow: hidden; width: 100%; white-space: nowrap;">------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
        </div>

    {% endif %}
</div>
